# Use Node base image
FROM node:18-alpine

# Install Angular CLI
RUN npm install -g @angular/cli

# Create app directory
WORKDIR /app

# Copy dependency files and install packages
COPY package*.json ./
RUN npm install

# Copy rest of the app source code
COPY . .

# Expose default Angular port
EXPOSE 4200

# Start the dev server
CMD ["ng", "serve", "--host", "0.0.0.0"]
